version: "3.9"
services:
  db:
    image: postgres:15.1-alpine
    env_file:
      - .env
    container_name: ${DB_CONTAINER_NAME}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
      
  app:
    container_name: ${APP_CONTAINER_NAME}
    build: 
     context: .
     dockerfile: ./build/Dockerfile
    depends_on:
    - db
    volumes:
      - ./:/app
    tty: true
    environment:
      - TZ=Asia/Tokyo
    ports:
      - 8080:8080
      
volumes:
  db: